package com.example.androidcoursehw

object CityRepository {
    val cities = arrayListOf(
        City(0, "Los Angeles", "Los Angeles , city, seat of Los Angeles county, southern California, U.S. It is the second most populous city and metropolitan area (after New York City) in the United States. The city sprawls across a broad coastal plain situated between mountains and the Pacific Ocean; the much larger Los Angeles county, which encompasses the city, contains some 90 other incorporated cities, including Beverly Hills, Pasadena, and Long Beach. The county also encompasses two of the Channel Islands, Santa Catalina and San Clemente; Mount San Antonio, familiarly known as Mount Baldy or Old Baldy, 10,046 feet (3,062 metres) high; more than 900 square miles (2,330 square km) of desert; and 75 miles (120 km) of seacoast.",
            R.drawable.losangelesphoto),
        City(1, "Moscow", "Moscow, Russian Moskva, city, capital of Russia, located in the far western part of the country. Since it was first mentioned in the chronicles of 1147, Moscow has played a vital role in Russian history. It became the capital of Muscovy (the Grand Principality of Moscow) in the late 13th century; hence, the people of Moscow are known as Muscovites. Today Moscow is not only the political centre of Russia but also the country’s most populous city and its industrial, cultural, scientific, and educational capital. For more than 600 years Moscow also has been the spiritual centre of the Russian",
            R.drawable.moscowphoto),
        City(2, "Saint Petersburg", "Saint Petersburg is a city on the shore of the Gulf of Finland. Established in 1703 by Peter the Great, Saint Petersburg was the capital of Russia for two centuries, and has witnessed some of the most important historical events. The city is often called \"Venice of the North\" because of its unique architecture. Petersburg is also very famous for its special creative atmosphere that attracts artists, poets, and dreamers.",
            R.drawable.saintpetersburgphoto),
        City(3, "New-York", "New York City, officially the City of New York, historically New Amsterdam, the Mayor, Alderman, and Commonality of the City of New York, and New Orange, byname the Big Apple, city and port located at the mouth of the Hudson River, southeastern New York state, northeastern U.S. It is the largest and most influential American metropolis, encompassing Manhattan and Staten islands, the western sections of Long Island, and a small portion of the New York state mainland to the north of Manhattan. New York City is in reality a collection of many neighbourhoods scattered among the city’s five boroughs—Manhattan, Brooklyn, the Bronx, Queens, and Staten Island—each exhibiting its own lifestyle.",
            R.drawable.nycphoto),
        City(4, "Dallas", "Dallas is a city in the U.S. state of Texas and the largest city and seat of Dallas County, with portions extending into Collin, Denton, Kaufman and Rockwall counties. With an estimated 2018 population of 1,345,076, it is the ninth most-populous city in the U.S. and third in Texas after Houston and San Antonio. Located in North Texas, the city of Dallas is the main core of the largest metropolitan area in the Southern United States and the largest inland metropolitan area in the U.S. that lacks any navigable link to the sea. ",
            R.drawable.dallasphoto)
    )
}